// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Cust_Empl_PicUp_tbls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cust_Empl_PicUp_tbls));
        
        string IMigrationMetadata.Id
        {
            get { return "201903090058144_Cust_Empl_PicUp_tbls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
